/*
 * Generated by JasperReports - 5/13/09 1:58 PM
 */
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.fill.*;

import java.util.*;
import java.math.*;
import java.text.*;
import java.io.*;
import java.net.*;

import net.sf.jasperreports.engine.*;
import java.util.*;
import net.sf.jasperreports.engine.data.*;


/**
 *
 */
public class pricing_domain_lot_1242215887037_379342 extends JREvaluator
{


    /**
     *
     */
    private JRFillParameter parameter_REPORT_LOCALE = null;
    private JRFillParameter parameter_REPORT_TIME_ZONE = null;
    private JRFillParameter parameter_REPORT_VIRTUALIZER = null;
    private JRFillParameter parameter_AD_Client_ID = null;
    private JRFillParameter parameter_REPORT_SCRIPTLET = null;
    private JRFillParameter parameter_AFGO_PurchaseLot_ID = null;
    private JRFillParameter parameter_REPORT_PARAMETERS_MAP = null;
    private JRFillParameter parameter_REPORT_CONNECTION = null;
    private JRFillParameter parameter_DateDoc = null;
    private JRFillParameter parameter_REPORT_CLASS_LOADER = null;
    private JRFillParameter parameter_REPORT_DATA_SOURCE = null;
    private JRFillParameter parameter_REPORT_URL_HANDLER_FACTORY = null;
    private JRFillParameter parameter_IS_IGNORE_PAGINATION = null;
    private JRFillParameter parameter_AFGO_PurchaseDomain_ID = null;
    private JRFillParameter parameter_REPORT_FORMAT_FACTORY = null;
    private JRFillParameter parameter_REPORT_MAX_COUNT = null;
    private JRFillParameter parameter_AD_Org_ID = null;
    private JRFillParameter parameter_REPORT_RESOURCE_BUNDLE = null;
    private JRFillField field_QREQUESTLINE = null;
    private JRFillField field_REQUESTTOTAL = null;
    private JRFillField field_RESPONSEPRICE = null;
    private JRFillField field_RESPONSEQTY = null;
    private JRFillField field_AFGO_PURCHASEDOMAIN_ID = null;
    private JRFillField field_RESPONSETOTAL = null;
    private JRFillField field_QRESPONSE = null;
    private JRFillField field_QRESPONSELINE = null;
    private JRFillField field_REQUESTLINENETAMT = null;
    private JRFillField field_REQUESTPRICE = null;
    private JRFillField field_AFGO_PURCHASELOT_ID = null;
    private JRFillField field_LOTITEM = null;
    private JRFillField field_ORGANIZATION = null;
    private JRFillField field_RESPONSELINENETAMT = null;
    private JRFillField field_REQUESTQTY = null;
    private JRFillField field_RESPONSEDATE = null;
    private JRFillField field_DOMAIN = null;
    private JRFillField field_LOT = null;
    private JRFillField field_QREQUEST = null;
    private JRFillVariable variable_PAGE_NUMBER = null;
    private JRFillVariable variable_COLUMN_NUMBER = null;
    private JRFillVariable variable_REPORT_COUNT = null;
    private JRFillVariable variable_PAGE_COUNT = null;
    private JRFillVariable variable_COLUMN_COUNT = null;


    /**
     *
     */
    public void customizedInit(
        Map pm,
        Map fm,
        Map vm
        )
    {
        initParams(pm);
        initFields(fm);
        initVars(vm);
    }


    /**
     *
     */
    private void initParams(Map pm)
    {
        parameter_REPORT_LOCALE = (JRFillParameter)pm.get("REPORT_LOCALE");
        parameter_REPORT_TIME_ZONE = (JRFillParameter)pm.get("REPORT_TIME_ZONE");
        parameter_REPORT_VIRTUALIZER = (JRFillParameter)pm.get("REPORT_VIRTUALIZER");
        parameter_AD_Client_ID = (JRFillParameter)pm.get("AD_Client_ID");
        parameter_REPORT_SCRIPTLET = (JRFillParameter)pm.get("REPORT_SCRIPTLET");
        parameter_AFGO_PurchaseLot_ID = (JRFillParameter)pm.get("AFGO_PurchaseLot_ID");
        parameter_REPORT_PARAMETERS_MAP = (JRFillParameter)pm.get("REPORT_PARAMETERS_MAP");
        parameter_REPORT_CONNECTION = (JRFillParameter)pm.get("REPORT_CONNECTION");
        parameter_DateDoc = (JRFillParameter)pm.get("DateDoc");
        parameter_REPORT_CLASS_LOADER = (JRFillParameter)pm.get("REPORT_CLASS_LOADER");
        parameter_REPORT_DATA_SOURCE = (JRFillParameter)pm.get("REPORT_DATA_SOURCE");
        parameter_REPORT_URL_HANDLER_FACTORY = (JRFillParameter)pm.get("REPORT_URL_HANDLER_FACTORY");
        parameter_IS_IGNORE_PAGINATION = (JRFillParameter)pm.get("IS_IGNORE_PAGINATION");
        parameter_AFGO_PurchaseDomain_ID = (JRFillParameter)pm.get("AFGO_PurchaseDomain_ID");
        parameter_REPORT_FORMAT_FACTORY = (JRFillParameter)pm.get("REPORT_FORMAT_FACTORY");
        parameter_REPORT_MAX_COUNT = (JRFillParameter)pm.get("REPORT_MAX_COUNT");
        parameter_AD_Org_ID = (JRFillParameter)pm.get("AD_Org_ID");
        parameter_REPORT_RESOURCE_BUNDLE = (JRFillParameter)pm.get("REPORT_RESOURCE_BUNDLE");
    }


    /**
     *
     */
    private void initFields(Map fm)
    {
        field_QREQUESTLINE = (JRFillField)fm.get("QREQUESTLINE");
        field_REQUESTTOTAL = (JRFillField)fm.get("REQUESTTOTAL");
        field_RESPONSEPRICE = (JRFillField)fm.get("RESPONSEPRICE");
        field_RESPONSEQTY = (JRFillField)fm.get("RESPONSEQTY");
        field_AFGO_PURCHASEDOMAIN_ID = (JRFillField)fm.get("AFGO_PURCHASEDOMAIN_ID");
        field_RESPONSETOTAL = (JRFillField)fm.get("RESPONSETOTAL");
        field_QRESPONSE = (JRFillField)fm.get("QRESPONSE");
        field_QRESPONSELINE = (JRFillField)fm.get("QRESPONSELINE");
        field_REQUESTLINENETAMT = (JRFillField)fm.get("REQUESTLINENETAMT");
        field_REQUESTPRICE = (JRFillField)fm.get("REQUESTPRICE");
        field_AFGO_PURCHASELOT_ID = (JRFillField)fm.get("AFGO_PURCHASELOT_ID");
        field_LOTITEM = (JRFillField)fm.get("LOTITEM");
        field_ORGANIZATION = (JRFillField)fm.get("ORGANIZATION");
        field_RESPONSELINENETAMT = (JRFillField)fm.get("RESPONSELINENETAMT");
        field_REQUESTQTY = (JRFillField)fm.get("REQUESTQTY");
        field_RESPONSEDATE = (JRFillField)fm.get("RESPONSEDATE");
        field_DOMAIN = (JRFillField)fm.get("DOMAIN");
        field_LOT = (JRFillField)fm.get("LOT");
        field_QREQUEST = (JRFillField)fm.get("QREQUEST");
    }


    /**
     *
     */
    private void initVars(Map vm)
    {
        variable_PAGE_NUMBER = (JRFillVariable)vm.get("PAGE_NUMBER");
        variable_COLUMN_NUMBER = (JRFillVariable)vm.get("COLUMN_NUMBER");
        variable_REPORT_COUNT = (JRFillVariable)vm.get("REPORT_COUNT");
        variable_PAGE_COUNT = (JRFillVariable)vm.get("PAGE_COUNT");
        variable_COLUMN_COUNT = (JRFillVariable)vm.get("COLUMN_COUNT");
    }


    /**
     *
     */
    public Object evaluate(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = (java.lang.Integer)(new Integer(1000000));/*$JR_EXPR_ID=0$*/
                break;
            }
            case 1 : 
            {
                value = (java.lang.Integer)(new Integer(1000000));/*$JR_EXPR_ID=1$*/
                break;
            }
            case 2 : 
            {
                value = (java.lang.Integer)(new Integer(1000004));/*$JR_EXPR_ID=2$*/
                break;
            }
            case 3 : 
            {
                value = (java.lang.Integer)(new Integer(1000005));/*$JR_EXPR_ID=3$*/
                break;
            }
            case 4 : 
            {
                value = (java.lang.String)("2008-02-06");/*$JR_EXPR_ID=4$*/
                break;
            }
            case 5 : 
            {
                value = (java.lang.Integer)(new Integer(1));/*$JR_EXPR_ID=5$*/
                break;
            }
            case 6 : 
            {
                value = (java.lang.Integer)(new Integer(1));/*$JR_EXPR_ID=6$*/
                break;
            }
            case 7 : 
            {
                value = (java.lang.Integer)(new Integer(1));/*$JR_EXPR_ID=7$*/
                break;
            }
            case 8 : 
            {
                value = (java.lang.Integer)(new Integer(0));/*$JR_EXPR_ID=8$*/
                break;
            }
            case 9 : 
            {
                value = (java.lang.Integer)(new Integer(1));/*$JR_EXPR_ID=9$*/
                break;
            }
            case 10 : 
            {
                value = (java.lang.Integer)(new Integer(0));/*$JR_EXPR_ID=10$*/
                break;
            }
            case 11 : 
            {
                value = (java.lang.Integer)(new Integer(1));/*$JR_EXPR_ID=11$*/
                break;
            }
            case 12 : 
            {
                value = (java.lang.Integer)(new Integer(0));/*$JR_EXPR_ID=12$*/
                break;
            }
            case 13 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)parameter_AFGO_PurchaseDomain_ID.getValue()));/*$JR_EXPR_ID=13$*/
                break;
            }
            case 14 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)parameter_AFGO_PurchaseLot_ID.getValue()));/*$JR_EXPR_ID=14$*/
                break;
            }
            case 15 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_DateDoc.getValue()));/*$JR_EXPR_ID=15$*/
                break;
            }
            case 16 : 
            {
                value = (java.lang.String)(((java.lang.String)field_DOMAIN.getValue()));/*$JR_EXPR_ID=16$*/
                break;
            }
            case 17 : 
            {
                value = (java.lang.String)(((java.lang.String)field_LOT.getValue()));/*$JR_EXPR_ID=17$*/
                break;
            }
            case 18 : 
            {
                value = (java.lang.String)(((java.lang.Integer)variable_PAGE_NUMBER.getValue()) +" "+ " van ");/*$JR_EXPR_ID=18$*/
                break;
            }
            case 19 : 
            {
                value = (java.lang.String)("" + ((java.lang.Integer)variable_PAGE_NUMBER.getValue()));/*$JR_EXPR_ID=19$*/
                break;
            }
            case 20 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)parameter_AD_Org_ID.getValue()));/*$JR_EXPR_ID=20$*/
                break;
            }
            case 21 : 
            {
                value = (java.lang.String)(((java.lang.String)field_ORGANIZATION.getValue()));/*$JR_EXPR_ID=21$*/
                break;
            }
            case 22 : 
            {
                value = (java.lang.String)(((java.lang.String)field_LOTITEM.getValue()));/*$JR_EXPR_ID=22$*/
                break;
            }
            case 23 : 
            {
                value = (java.lang.String)(((java.lang.String)field_QREQUEST.getValue()));/*$JR_EXPR_ID=23$*/
                break;
            }
            case 24 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_QREQUESTLINE.getValue()));/*$JR_EXPR_ID=24$*/
                break;
            }
            case 25 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_REQUESTQTY.getValue()));/*$JR_EXPR_ID=25$*/
                break;
            }
            case 26 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_REQUESTPRICE.getValue()));/*$JR_EXPR_ID=26$*/
                break;
            }
            case 27 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_REQUESTLINENETAMT.getValue()));/*$JR_EXPR_ID=27$*/
                break;
            }
            case 28 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_REQUESTTOTAL.getValue()));/*$JR_EXPR_ID=28$*/
                break;
            }
            case 29 : 
            {
                value = (java.lang.String)(((java.lang.String)field_QRESPONSE.getValue()));/*$JR_EXPR_ID=29$*/
                break;
            }
            case 30 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_QRESPONSELINE.getValue()));/*$JR_EXPR_ID=30$*/
                break;
            }
            case 31 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_RESPONSEQTY.getValue()));/*$JR_EXPR_ID=31$*/
                break;
            }
            case 32 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_RESPONSEPRICE.getValue()));/*$JR_EXPR_ID=32$*/
                break;
            }
            case 33 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_RESPONSELINENETAMT.getValue()));/*$JR_EXPR_ID=33$*/
                break;
            }
            case 34 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_RESPONSETOTAL.getValue()));/*$JR_EXPR_ID=34$*/
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateOld(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = (java.lang.Integer)(new Integer(1000000));/*$JR_EXPR_ID=0$*/
                break;
            }
            case 1 : 
            {
                value = (java.lang.Integer)(new Integer(1000000));/*$JR_EXPR_ID=1$*/
                break;
            }
            case 2 : 
            {
                value = (java.lang.Integer)(new Integer(1000004));/*$JR_EXPR_ID=2$*/
                break;
            }
            case 3 : 
            {
                value = (java.lang.Integer)(new Integer(1000005));/*$JR_EXPR_ID=3$*/
                break;
            }
            case 4 : 
            {
                value = (java.lang.String)("2008-02-06");/*$JR_EXPR_ID=4$*/
                break;
            }
            case 5 : 
            {
                value = (java.lang.Integer)(new Integer(1));/*$JR_EXPR_ID=5$*/
                break;
            }
            case 6 : 
            {
                value = (java.lang.Integer)(new Integer(1));/*$JR_EXPR_ID=6$*/
                break;
            }
            case 7 : 
            {
                value = (java.lang.Integer)(new Integer(1));/*$JR_EXPR_ID=7$*/
                break;
            }
            case 8 : 
            {
                value = (java.lang.Integer)(new Integer(0));/*$JR_EXPR_ID=8$*/
                break;
            }
            case 9 : 
            {
                value = (java.lang.Integer)(new Integer(1));/*$JR_EXPR_ID=9$*/
                break;
            }
            case 10 : 
            {
                value = (java.lang.Integer)(new Integer(0));/*$JR_EXPR_ID=10$*/
                break;
            }
            case 11 : 
            {
                value = (java.lang.Integer)(new Integer(1));/*$JR_EXPR_ID=11$*/
                break;
            }
            case 12 : 
            {
                value = (java.lang.Integer)(new Integer(0));/*$JR_EXPR_ID=12$*/
                break;
            }
            case 13 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)parameter_AFGO_PurchaseDomain_ID.getValue()));/*$JR_EXPR_ID=13$*/
                break;
            }
            case 14 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)parameter_AFGO_PurchaseLot_ID.getValue()));/*$JR_EXPR_ID=14$*/
                break;
            }
            case 15 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_DateDoc.getValue()));/*$JR_EXPR_ID=15$*/
                break;
            }
            case 16 : 
            {
                value = (java.lang.String)(((java.lang.String)field_DOMAIN.getOldValue()));/*$JR_EXPR_ID=16$*/
                break;
            }
            case 17 : 
            {
                value = (java.lang.String)(((java.lang.String)field_LOT.getOldValue()));/*$JR_EXPR_ID=17$*/
                break;
            }
            case 18 : 
            {
                value = (java.lang.String)(((java.lang.Integer)variable_PAGE_NUMBER.getOldValue()) +" "+ " van ");/*$JR_EXPR_ID=18$*/
                break;
            }
            case 19 : 
            {
                value = (java.lang.String)("" + ((java.lang.Integer)variable_PAGE_NUMBER.getOldValue()));/*$JR_EXPR_ID=19$*/
                break;
            }
            case 20 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)parameter_AD_Org_ID.getValue()));/*$JR_EXPR_ID=20$*/
                break;
            }
            case 21 : 
            {
                value = (java.lang.String)(((java.lang.String)field_ORGANIZATION.getOldValue()));/*$JR_EXPR_ID=21$*/
                break;
            }
            case 22 : 
            {
                value = (java.lang.String)(((java.lang.String)field_LOTITEM.getOldValue()));/*$JR_EXPR_ID=22$*/
                break;
            }
            case 23 : 
            {
                value = (java.lang.String)(((java.lang.String)field_QREQUEST.getOldValue()));/*$JR_EXPR_ID=23$*/
                break;
            }
            case 24 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_QREQUESTLINE.getOldValue()));/*$JR_EXPR_ID=24$*/
                break;
            }
            case 25 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_REQUESTQTY.getOldValue()));/*$JR_EXPR_ID=25$*/
                break;
            }
            case 26 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_REQUESTPRICE.getOldValue()));/*$JR_EXPR_ID=26$*/
                break;
            }
            case 27 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_REQUESTLINENETAMT.getOldValue()));/*$JR_EXPR_ID=27$*/
                break;
            }
            case 28 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_REQUESTTOTAL.getOldValue()));/*$JR_EXPR_ID=28$*/
                break;
            }
            case 29 : 
            {
                value = (java.lang.String)(((java.lang.String)field_QRESPONSE.getOldValue()));/*$JR_EXPR_ID=29$*/
                break;
            }
            case 30 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_QRESPONSELINE.getOldValue()));/*$JR_EXPR_ID=30$*/
                break;
            }
            case 31 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_RESPONSEQTY.getOldValue()));/*$JR_EXPR_ID=31$*/
                break;
            }
            case 32 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_RESPONSEPRICE.getOldValue()));/*$JR_EXPR_ID=32$*/
                break;
            }
            case 33 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_RESPONSELINENETAMT.getOldValue()));/*$JR_EXPR_ID=33$*/
                break;
            }
            case 34 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_RESPONSETOTAL.getOldValue()));/*$JR_EXPR_ID=34$*/
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateEstimated(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = (java.lang.Integer)(new Integer(1000000));/*$JR_EXPR_ID=0$*/
                break;
            }
            case 1 : 
            {
                value = (java.lang.Integer)(new Integer(1000000));/*$JR_EXPR_ID=1$*/
                break;
            }
            case 2 : 
            {
                value = (java.lang.Integer)(new Integer(1000004));/*$JR_EXPR_ID=2$*/
                break;
            }
            case 3 : 
            {
                value = (java.lang.Integer)(new Integer(1000005));/*$JR_EXPR_ID=3$*/
                break;
            }
            case 4 : 
            {
                value = (java.lang.String)("2008-02-06");/*$JR_EXPR_ID=4$*/
                break;
            }
            case 5 : 
            {
                value = (java.lang.Integer)(new Integer(1));/*$JR_EXPR_ID=5$*/
                break;
            }
            case 6 : 
            {
                value = (java.lang.Integer)(new Integer(1));/*$JR_EXPR_ID=6$*/
                break;
            }
            case 7 : 
            {
                value = (java.lang.Integer)(new Integer(1));/*$JR_EXPR_ID=7$*/
                break;
            }
            case 8 : 
            {
                value = (java.lang.Integer)(new Integer(0));/*$JR_EXPR_ID=8$*/
                break;
            }
            case 9 : 
            {
                value = (java.lang.Integer)(new Integer(1));/*$JR_EXPR_ID=9$*/
                break;
            }
            case 10 : 
            {
                value = (java.lang.Integer)(new Integer(0));/*$JR_EXPR_ID=10$*/
                break;
            }
            case 11 : 
            {
                value = (java.lang.Integer)(new Integer(1));/*$JR_EXPR_ID=11$*/
                break;
            }
            case 12 : 
            {
                value = (java.lang.Integer)(new Integer(0));/*$JR_EXPR_ID=12$*/
                break;
            }
            case 13 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)parameter_AFGO_PurchaseDomain_ID.getValue()));/*$JR_EXPR_ID=13$*/
                break;
            }
            case 14 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)parameter_AFGO_PurchaseLot_ID.getValue()));/*$JR_EXPR_ID=14$*/
                break;
            }
            case 15 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_DateDoc.getValue()));/*$JR_EXPR_ID=15$*/
                break;
            }
            case 16 : 
            {
                value = (java.lang.String)(((java.lang.String)field_DOMAIN.getValue()));/*$JR_EXPR_ID=16$*/
                break;
            }
            case 17 : 
            {
                value = (java.lang.String)(((java.lang.String)field_LOT.getValue()));/*$JR_EXPR_ID=17$*/
                break;
            }
            case 18 : 
            {
                value = (java.lang.String)(((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue()) +" "+ " van ");/*$JR_EXPR_ID=18$*/
                break;
            }
            case 19 : 
            {
                value = (java.lang.String)("" + ((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue()));/*$JR_EXPR_ID=19$*/
                break;
            }
            case 20 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)parameter_AD_Org_ID.getValue()));/*$JR_EXPR_ID=20$*/
                break;
            }
            case 21 : 
            {
                value = (java.lang.String)(((java.lang.String)field_ORGANIZATION.getValue()));/*$JR_EXPR_ID=21$*/
                break;
            }
            case 22 : 
            {
                value = (java.lang.String)(((java.lang.String)field_LOTITEM.getValue()));/*$JR_EXPR_ID=22$*/
                break;
            }
            case 23 : 
            {
                value = (java.lang.String)(((java.lang.String)field_QREQUEST.getValue()));/*$JR_EXPR_ID=23$*/
                break;
            }
            case 24 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_QREQUESTLINE.getValue()));/*$JR_EXPR_ID=24$*/
                break;
            }
            case 25 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_REQUESTQTY.getValue()));/*$JR_EXPR_ID=25$*/
                break;
            }
            case 26 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_REQUESTPRICE.getValue()));/*$JR_EXPR_ID=26$*/
                break;
            }
            case 27 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_REQUESTLINENETAMT.getValue()));/*$JR_EXPR_ID=27$*/
                break;
            }
            case 28 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_REQUESTTOTAL.getValue()));/*$JR_EXPR_ID=28$*/
                break;
            }
            case 29 : 
            {
                value = (java.lang.String)(((java.lang.String)field_QRESPONSE.getValue()));/*$JR_EXPR_ID=29$*/
                break;
            }
            case 30 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_QRESPONSELINE.getValue()));/*$JR_EXPR_ID=30$*/
                break;
            }
            case 31 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_RESPONSEQTY.getValue()));/*$JR_EXPR_ID=31$*/
                break;
            }
            case 32 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_RESPONSEPRICE.getValue()));/*$JR_EXPR_ID=32$*/
                break;
            }
            case 33 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_RESPONSELINENETAMT.getValue()));/*$JR_EXPR_ID=33$*/
                break;
            }
            case 34 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_RESPONSETOTAL.getValue()));/*$JR_EXPR_ID=34$*/
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


}
